<template>
  <div class="box home">
    <input class="input" v-model="childAge" placeholder="سن کودک خود را وارد کنید" /><br>
    <select class="input" v-model="childGender">
      <option disabled value="">لطفا جنسیت کودک خود را امتخاب کنید</option>
      <option>پسر</option>
      <option>دختر</option>
      <option>نامعلوم</option>
    </select>
    <Survey
      @goNext="showNextQuestion"
      :survey="survey"
      @goPrev="showPrevQuestion"
    />
  </div>
</template>



<script>
import Survey from "../components/Survey.vue";
// import jsonData from "../json/survey.json"

export default {
  name: "Home",
  components: {
    Survey,
  },

  methods: {
    showNextQuestion(id) {
      console.log(id);
      if (id == 1) {
        this.survey[id].isAnswered = true;
        this.survey[id].isSelected = false;

        this.parentChoices = [];
        this.survey.forEach((element) => {
          this.parentChoices.push(element.choice);
        });
        let finalString = this.parentChoices.toString();
        console.log("choices are JSON: ", JSON.stringify(this.parentChoices));
        console.log("choices are STRING:", finalString);
      } else {
        this.survey[id].isAnswered = true;
        this.survey[id].isSelected = false;
        this.survey[id + 1].isSelected = true;
      }
    },
    showPrevQuestion(id) {
      if (id != 0) {
        console.log(id);
        this.survey[id].isSelected = false;
        this.survey[id - 1].isSelected = true;
      } else {
        alert("سوال قبلی ای وجود ندارد");
      }
    },
  },

  data() {
    return {
      survey: [],
      parentChoices: [],
      childAge: "",
      childGender:"",
    };
  },

  created() {
    this.survey = [
      {
        id: 0,
        title: "خودآگاهی هیجانی",
        value: "Emotional_self-awareness1",
        text: "بیشتر اوقات فرزندم متوجه نمیشود چه احساسی دارد‬",
        isAnswered: false,
        choice: "",
        isSelected: true,
      },
      {
        id: 1,
        title: "خودآگاهی هیجانی",
        value: "Emotional_self-awareness2",
        text: "وقتی یکی از دوستانش ناراحت باشد او متوجه نمیشود.",
        isAnswered: false,
        choice: "",
        isSelected: false,
      },
      // {
      //   id: 2,
      //   title: "خودآگاهی هیجانی",
      //   value: "Emotional_self-awareness3",
      //   text: "دقيقا مى داند چه احساسى دارد.",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 3,
      //   title: "خودآگاهی هیجانی",
      //   value: "Emotional_self-awareness4",
      //   text: "احساسات دیگران را میفهمد",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 4,
      //   title: "خودآگاهی هیجانی",
      //   value: "Emotional_self-awareness5",
      //   text: "درك احساسات ديگران برايش دشوار است.",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 5,
      //   title: "خودآگاهی هیجانی",
      //   value: "Emotional_self-awareness6",
      //   text: "عصبانیت دیگران را تشخیص میدهد.",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 6,
      //   title: "خودآگاهی هیجانی",
      //   value: "Emotional_self-awareness7",
      //   text: "احساسات خود را به سادگی درک میکند.",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 7,
      //   title: "خودآگاهی هیجانی",
      //   value: "Emotional_self-awareness8",
      //   text: "بیشتر مواقع درمورد درک احساسی که دارد ناتوان است",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 8,
      //   title: "خودآگاهی هیجانی",
      //   value: "Emotional_self-awareness9",
      //   text: "بیشتر مواقع احساس ناراحتی میکند ولی علت آن را نمیداند.",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 9,
      //   title: "خودآگاهی هیجانی",
      //   value: "Emotional_self-awareness10",
      //   text: "زمانی که چیزی او را ناراحت میکند نمیتواند تشخیص دهد.",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 10,
      //   title: "خودآگاهی هیجانی",
      //   value: "Emotional_self-awareness11",
      //   text: "صحبت کردن درمورد اینکه  چه احساسی دارد برایش سخت است.",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 11,
      //   title: "خودآگاهی هیجانی",
      //   value: "Emotional_self-awareness12",
      //   text: "هیچ توچهی به هیجانات دیگران ندارد",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 12,
      //   title: "تنظیم هیجانات",
      //   value: "EmotionRegulation_1",
      //   text: "وقتی غمگین باشد سعی می کند خود را مشغول کند",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 13,
      //   title: "تنظیم هیجانات",
      //   value: "EmotionRegulation_2",
      //   text: " .همیشه سعی دارد بهترین اخلاق را داشته باشد",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 14,
      //   title: "تنظیم هیجانات",
      //   value: "EmotionRegulation_3",
      //   text: "وقتی ناراحت باشد سعی می کند خود را خوشحال نشان دهد",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 15,
      //   title: "تنظیم هیجانات",
      //   value: "EmotionRegulation_4",
      //   text: " .اگر در امتحانی موفق نشود، در امتحان بعدی سخت تر تلاش می کند. ",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 16,
      //   title: "تنظیم هیجانات",
      //   value: "EmotionRegulation_5",
      //   text: " .در کنترل احساسات خود موفق است.",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 17,
      //   title: "تنظیم هیجانات",
      //   value: "EmotionRegulation_6",
      //   text: "می تواند هیجاناتش را کنترل کند",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   id: 18,
      //   title: "تنظیم هیجانات",
      //   value: "EmotionRegulation_7",
      //   text: ".بی دلیل هیجان زده نمی شود یا از شدت هیجان اشک در چشمانش حلقه نمی زند. ",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_1",
      //   text: " .هر چیزی که بخواهد، بلافاصله باید به آن برسد.",
      //   id: 19,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_2",
      //   text: "دوست ندارد برای چیزی که می خواهد منتظر بماند",
      //   id: 20,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_3",
      //   text: "هرکاری را که بخواهد انجام می دهد بدون اینکه در مورد آن فکر کند.",
      //   id: 21,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_4",
      //   text: " .خیلی وقت ها قبل از انجام دادن کارها فکر نمی کند.",
      //   id: 22,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_5",
      //   text: " .در موقعیت تعارض با همساالن خشم خود را کنترل می کند",
      //   id: 23,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_6",
      //   text: "فرزندم به آسانی عصبانی می شود.",
      //   id: 24,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_7",
      //   text: "فرزندم اغلب اوقات نق می زند یا شکایت می کند. ",
      //   id: 25,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_8",
      //   text: "فرزندم وقتی عصبانی می شود دیگران را کتک می زند. ",
      //   id: 26,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_9",
      //   text: "وسط حرف دیگران می پرد و حرفشان را قطع می کند",
      //   id: 27,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_10",
      //   text: " .عادت های تکانشی دارد که نمی تواند جلوی آن ها را بگیرد. ",
      //   id: 28,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_11",
      //   text: ".قبل از تصمیم گیری، راه حل های مختلف را در نظر می گیرد",
      //   id: 29,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ImpactControl_12",
      //   text: "رفتار یا گفتتاری از او سر می زند که باعث پشیمانی او می شود. ",
      //   id: 30,
      //   title: "کنترل تکانه",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ProblemSolving_1",
      //   text: "هنگامی که ناراحت یا عصبانی است سعی می کند دلیل آن را بفهمد",
      //   id: 31,
      //   title: "حل مسئله",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ProblemSolving_2",
      //   text: " .با تحلیل احساسات خود، سعی می کند دلیل اتفاقاتی که برایش افتاده را پیدا کند.",
      //   id: 32,
      //   title: "حل مسئله",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ProblemSolving_3",
      //   text: "همیشه می خواهد دلیل اینکه چرا احساسات بدی داشته را پیدا کند",
      //   id: 33,
      //   title: "حل مسئله",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ProblemSolving_4",
      //   text: "در شرایط استرس زا یک راهی پیدا می کند تا خود را آرام کند.",
      //   id: 34,
      //   title: "حل مسئله",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ProblemSolving_5",
      //   text: "معموال مشکلاتش را خودش حل می کند",
      //   id: 35,
      //   title: "حل مسئله",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ProblemSolving_6",
      //   text: "به طور موثر تعارض و مشکلات را حل می کند",
      //   id: 36,
      //   title: "حل مسئله",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "ProblemSolving_7",
      //   text: "وقتی از مشکلات دیگران باخبر شود، به سرعت راه حل های مختلفی به ذهن آن خطور می کند. ",
      //   id: 37,
      //   title: "حل مسئله",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "flexibility_1",
      //   text: "به راحتی میتواند به چیزهای جدید عادت کند.",
      //   id: 38,
      //   title: "انعطاف پذیری",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "flexibility_2",
      //   text: "عادت کردن به سال تحصیلی برایش دشوار است. ",
      //   id: 39,
      //   title: "انعطاف پذیری",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "flexibility_3",
      //   text: "وقتی در محل جدید باشد به سرعت به آن عادت می کند. ",
      //   id: 40,
      //   title: "انعطاف پذیری",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "flexibility_4",
      //   text: " .دوست ندارد به کارهای جدید دست بزند. ",
      //   id: 41,
      //   title: "انعطاف پذیری",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "flexibility_5",
      //   text: "می تواند رسیدن به خواسته های خود را به تاخیر بیندازد و منتظر بماند تا به خواسته هایش برسد.",
      //   id: 42,
      //   title: "انعطاف پذیری",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "flexibility_6",
      //   text: "وقتی مجبور باشد کاری را انجام دهد، دچار خشم و عصبانیت می شود.",
      //   id: 43,
      //   title: "انعطاف پذیری",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "flexibility_7",
      //   text: " .دوست دارد چیزهای جدیدی یاد بگیرد",
      //   id: 44,
      //   title: "انعطاف پذیری",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "flexibility_8",
      //   text: "در مواجه با اتفاقات انعطاف پذیر عمل می کند. ",
      //   id: 45,
      //   title: "انعطاف پذیری",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "Sympathy_1",
      //   text: "فرندم دوستش را که غمگین است، دلداری میدهد.",
      //   id: 46,
      //   title: "همدردی",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "Sympathy_2",
      //   text: "فرزندم دوستی را که رنجیده باشد کمک می کند.",
      //   id: 47,
      //   title: "همدردی",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "Sympathy_3",
      //   text: " .او شنونده ی خوبی برای دیگران است",
      //   id: 48,
      //   title: "همدردی",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "Sympathy_4",
      //   text: "می تواند با دیگران همدردی کند.",
      //   id: 49,
      //   title: "همدردی",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "Sympathy_5",
      //   text: " .دیگران را به خوبی درک می کند. ",
      //   id: 50,
      //   title: "همدردی",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "Sympathy_6",
      //   text: "براساس درک احساسات و نیازهای دیگران به آن ها کمک می کند.",
      //   id: 51,
      //   title: "همدردی",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_1",
      //   text: "حیلی راحت دوست پیدا می کند. ",
      //   id: 52,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_2",
      //   text: "دوست ندارد با بچه هایی که نمی شناسد حرف بزند. ",
      //   id: 52,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_3",
      //   text: "دوستان زیادی دارد. ",
      //   id: 53,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_4",
      //   text: "دوست دارد افراد جدید را ببیند. ",
      //   id: 54,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_5",
      //   text: "دوست دارد با دیگران باشد. ",
      //   id: 55,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_6",
      //   text: "با همه کنار می آید. ",
      //   id: 56,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_7",
      //   text: ".اغلب با دیگران دعوا می کند. ",
      //   id: 57,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_8",
      //   text: ".دیگران بازی کردن با او را دوست دارند. ",
      //   id: 58,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_9",
      //   text: "با همکالسی هایش همکاری و مشارکت می کند. ",
      //   id: 59,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_10",
      //   text: "در صحبت با همساالن پیش قدم می شود. ",
      //   id: 60,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_11",
      //   text: ".با دوستان خود همکاری می کند. ",
      //   id: 61,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_12",
      //   text: ".در بازی های گروهی به خوبی با دیگران کنار می آید. ",
      //   id: 62,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_13",
      //   text: " .دوست دارد تنها بازی کند. ",
      //   id: 63,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_14",
      //   text: ".فرزندم می داند که چطور دوست پیدا کند. ",
      //   id: 64,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      // {
      //   value: "PeersRelationships_15",
      //   text: "در بازی های گروهی شرکت می کند. ",
      //   id: 65,
      //   title: "رابطه با همسالان",
      //   isAnswered: false,
      //   choice: "",
      //   isSelected: false,
      // },
      {
        value: "",
        text: "",
        id: 66,
        title: "",
        isAnswered: false,
        choice: "",
        isSelected: false,
      },
    ];
  },
};
</script>

<style scoped>
</style>