# Generated by Django 3.2.10 on 2021-12-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childAge', models.IntegerField()),
                ('childGender', models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'MALE'), (2, 'FEMALE'), (9, 'NOTAPPLICABLE')])),
                ('parentAnswerArray', models.CharField(max_length=100)),
            ],
        ),
    ]
