# Generated by Django 3.2.10 on 2021-12-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswers',
            name='childGender',
            field=models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'MALE'), (2, 'FEMALE'), (9, 'NOT_APPLICABLE')]),
        ),
    ]
