# Generated by Django 3.2.10 on 2021-12-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0003_parentquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentquestions',
            name='choices',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
    ]
