# Generated by Django 3.2.10 on 2021-12-24 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0004_alter_parentquestions_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentquestions',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='parentquestions',
            name='isAnswered',
        ),
        migrations.RemoveField(
            model_name='parentquestions',
            name='isSelected',
        ),
    ]
