# Generated by Django 3.2.10 on 2022-01-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0005_auto_20211224_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('value0', models.IntegerField()),
                ('answer0', models.CharField(max_length=150)),
                ('value1', models.IntegerField()),
                ('answer1', models.CharField(max_length=150)),
                ('value2', models.IntegerField()),
                ('answer2', models.CharField(max_length=150)),
            ],
        ),
    ]
