# Generated by Django 3.2.10 on 2022-01-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0006_childquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSurveyAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childAnswerArray', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
