# Generated by Django 3.2.10 on 2022-01-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0007_childsurveyanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswers',
            name='parentAnswerArray',
            field=models.CharField(max_length=150),
        ),
    ]
