# Generated by Django 3.2.10 on 2022-01-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0008_alter_surveyanswers_parentanswerarray'),
    ]

    operations = [
        migrations.AddField(
            model_name='childquestion',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
